version: 2
updates:
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45

    cooldown:
      default-days: 45
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45
  - package-ecosystem: "docker"
    directory: "/src/caddy"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45
