name: branch-deploy

on:
  issue_comment:
    types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  deploy:
    environment:
      name: production
      deployment: false # don't create a deployment in GitHub, we just want the environment protection rules and fetching secrets
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments
    runs-on: ubuntu-latest

    steps:
      - uses: github/branch-deploy@v11
        id: branch-deploy
        with:
          admins: the-hideout/core-contributors
          admins_pat: ${{ secrets.BRANCH_DEPLOY_ADMINS_PAT }}
          environment_targets: production
          sticky_locks: "true"

      - name: fetch repo name
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        id: repo_name
        run: echo "repo_name=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_OUTPUT

      - name: checkout
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.branch-deploy.outputs.sha }}

      - name: ssh remote deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # pin@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: ~/${{ steps.repo_name.outputs.repo_name }}/script/deploy -r "${{ steps.branch-deploy.outputs.sha }}" -f "${{ steps.branch-deploy.outputs.fork_checkout }}" -d "/home/${{ secrets.SSH_USERNAME }}/${{ steps.repo_name.outputs.repo_name }}" -n "${{ steps.branch-deploy.outputs.fork_full_name }}"
