name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push'
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: deployment check
        uses: github/branch-deploy@v11
        id: deployment-check
        with:
          merge_deploy_mode: "true"
          environment: production

      - name: fetch repo name
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        id: repo_name
        run: echo "repo_name=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_OUTPUT

      - name: checkout
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.deployment-check.outputs.sha }}

      - name: ssh remote deploy
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # pin@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: ~/${{ steps.repo_name.outputs.repo_name }}/script/deploy -r "main" -d "/home/${{ secrets.SSH_USERNAME }}/${{ steps.repo_name.outputs.repo_name }}"
